[project]
name = "alignments"
version = "0.0.1"
description = ""
authors = [
    {name = "Christoph Minixhofer", email = "christoph.minixhofer@gmail.com"},
]
dependencies = [
    "click>=8.0.4",
    "rich>=10.11.0",
]
requires-python = ">=3.6"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.scripts]
alignments = "alignments:cli"

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
